-- ── Seed: 40 sample opportunities (10 per type) ───────────────────────────────
-- Cyprus / EU student-oriented realistic data
-- Run after the opportunities migration

INSERT INTO opportunities (
  type, title, description, organization, location, location_type,
  url, image_url, source, source_id,
  starts_at, ends_at,
  salary_min, salary_max, salary_currency,
  employment_type, tags
) VALUES

-- ─────────────────────────────────────────────────────────────────────────────
-- 10 EVENTS
-- ─────────────────────────────────────────────────────────────────────────────

('event',
 'Cyprus Tech Summit 2025',
 'Annual technology conference bringing together students, developers, and industry professionals from across Cyprus and the wider Mediterranean region. Featuring keynotes, workshops, and a startup showcase.',
 'Cyprus Chamber of Commerce and Industry',
 'Nicosia',
 'in_person',
 'https://example.com/cyprus-tech-summit',
 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
 'manual', 'seed-event-001',
 '2025-06-15 09:00:00+00', '2025-06-15 18:00:00+00',
 null, null, 'EUR', null,
 ARRAY['tech','networking','student-friendly']),

('event',
 'EU Green Futures Forum',
 'A pan-European sustainability forum hosted in Limassol, covering climate policy, circular economy, and green careers for students. Includes EU Commission speakers and NGO panels.',
 'European Commission Representation in Cyprus',
 'Limassol',
 'hybrid',
 'https://example.com/eu-green-futures',
 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=800',
 'manual', 'seed-event-002',
 '2025-07-04 10:00:00+00', '2025-07-05 17:00:00+00',
 null, null, 'EUR', null,
 ARRAY['sustainability','networking','student-friendly','entry-level']),

('event',
 'UX & Design Thinking Workshop',
 'Hands-on full-day workshop on user experience research, wireframing, and prototyping tools. Ideal for design and computer science students. Certificates provided.',
 'Cyprus Interaction Design Association',
 'Nicosia',
 'in_person',
 'https://example.com/ux-workshop-cy',
 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=800',
 'manual', 'seed-event-003',
 '2025-06-28 09:30:00+00', '2025-06-28 17:30:00+00',
 null, null, 'EUR', null,
 ARRAY['design','tech','student-friendly']),

('event',
 'Startup Weekend Limassol',
 '54-hour entrepreneurship event where students pitch ideas, form teams, and build startups from scratch. Mentors from leading Cyprus VC firms and corporates on-site throughout the weekend.',
 'Techstars Startup Weekend',
 'Limassol',
 'in_person',
 'https://example.com/startup-weekend-limassol',
 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800',
 'manual', 'seed-event-004',
 '2025-09-05 18:00:00+00', '2025-09-07 20:00:00+00',
 null, null, 'EUR', null,
 ARRAY['entrepreneurship','tech','networking','student-friendly']),

('event',
 'Mediterranean Career Fair 2025',
 'The largest graduate career fair in Cyprus, attracting 80+ employers from finance, tech, shipping, and healthcare sectors. CV clinics, speed networking, and on-the-spot interviews available.',
 'University of Cyprus Career Services',
 'Nicosia',
 'in_person',
 'https://example.com/med-career-fair',
 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800',
 'manual', 'seed-event-005',
 '2025-10-22 09:00:00+00', '2025-10-22 17:00:00+00',
 null, null, 'EUR', null,
 ARRAY['careers','networking','finance','tech','student-friendly']),

('event',
 'AI & Machine Learning Bootcamp',
 'Intensive 3-day bootcamp covering Python, scikit-learn, deep learning fundamentals, and real-world project deployment. Participants receive a digital certificate and access to a private Discord community.',
 'DataCamp Cyprus Hub',
 'Remote',
 'remote',
 'https://example.com/ai-bootcamp-cy',
 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800',
 'manual', 'seed-event-006',
 '2025-08-11 08:00:00+00', '2025-08-13 17:00:00+00',
 null, null, 'EUR', null,
 ARRAY['tech','remote','student-friendly','entry-level']),

('event',
 'Fintech Innovation Day',
 'A one-day conference focused on payments, blockchain, and digital banking innovation in the Eastern Mediterranean. Panel discussions and live product demos from leading Cyprus fintech startups.',
 'Cyprus Fintech Association',
 'Nicosia',
 'in_person',
 'https://example.com/fintech-day-cy',
 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800',
 'manual', 'seed-event-007',
 '2025-11-07 09:00:00+00', '2025-11-07 18:00:00+00',
 null, null, 'EUR', null,
 ARRAY['finance','tech','networking']),

('event',
 'Health & Wellbeing on Campus Symposium',
 'Student-led symposium exploring mental health resources, nutrition science, and physical wellbeing. Features talks from psychologists, dietitians, and university counsellors across Cyprus.',
 'Cyprus University Technology Health Board',
 'Limassol',
 'in_person',
 'https://example.com/health-campus-cy',
 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800',
 'manual', 'seed-event-008',
 '2025-05-30 10:00:00+00', '2025-05-30 16:00:00+00',
 null, null, 'EUR', null,
 ARRAY['healthcare','student-friendly']),

('event',
 'Digital Marketing Masterclass',
 'Full-day masterclass covering SEO, paid social, email automation, and analytics. Includes hands-on Google Ads and Meta Ads sandbox sessions. Open to all university students.',
 'Marketing Institute of Cyprus',
 'Nicosia',
 'hybrid',
 'https://example.com/digital-marketing-cy',
 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=800',
 'manual', 'seed-event-009',
 '2025-07-19 09:00:00+00', '2025-07-19 17:00:00+00',
 null, null, 'EUR', null,
 ARRAY['marketing','tech','student-friendly','entry-level']),

('event',
 'Architecture & Urban Design Expo',
 'Biennial exhibition and lecture series showcasing sustainable architecture projects by Cyprus students, young professionals, and established firms. Networking reception on the final evening.',
 'Cyprus Architects Association',
 'Paphos',
 'in_person',
 'https://example.com/arch-expo-cy',
 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800',
 'manual', 'seed-event-010',
 '2025-09-20 10:00:00+00', '2025-09-22 18:00:00+00',
 null, null, 'EUR', null,
 ARRAY['design','sustainability','networking']),

-- ─────────────────────────────────────────────────────────────────────────────
-- 10 JOBS
-- ─────────────────────────────────────────────────────────────────────────────

('job',
 'Junior Frontend Developer',
 'Join our product team building the next generation of fintech dashboards. You will work with React, TypeScript, and Tailwind CSS to deliver pixel-perfect UIs. Remote-friendly, with optional Nicosia office access.',
 'Payabl. (formerly Connectum)',
 'Nicosia',
 'hybrid',
 'https://example.com/jobs/payabl-frontend',
 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800',
 'manual', 'seed-job-001',
 '2025-06-01 00:00:00+00', null,
 1400, 1900, 'EUR',
 'full_time',
 ARRAY['tech','finance','entry-level','paid']),

('job',
 'Marketing Coordinator',
 'We are looking for a creative and data-driven marketing coordinator to support digital campaigns, social media management, and content creation for a growing Limassol-based travel-tech company.',
 'Travelplanet24 Cyprus',
 'Limassol',
 'in_person',
 'https://example.com/jobs/tp24-marketing',
 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800',
 'manual', 'seed-job-002',
 '2025-06-10 00:00:00+00', null,
 1200, 1600, 'EUR',
 'full_time',
 ARRAY['marketing','entry-level','paid','student-friendly']),

('job',
 'Data Analyst – Shipping Operations',
 'Support the analytics team at one of Cyprus''s leading shipping groups. Responsibilities include KPI dashboards in Power BI, SQL data wrangling, and monthly performance reports for the board.',
 'Columbia Shipmanagement',
 'Limassol',
 'in_person',
 'https://example.com/jobs/columbia-analyst',
 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800',
 'manual', 'seed-job-003',
 '2025-07-01 00:00:00+00', null,
 1600, 2200, 'EUR',
 'full_time',
 ARRAY['tech','finance','entry-level','paid']),

('job',
 'Customer Support Specialist (German-speaking)',
 'Provide first-class support to our European client base via chat and email. Fluent German and English required. Full training provided. Work from home with monthly team meetups in Nicosia.',
 'Exness Group',
 'Remote',
 'remote',
 'https://example.com/jobs/exness-support-de',
 'https://images.unsplash.com/photo-1556742044-3c52d6e88c62?w=800',
 'manual', 'seed-job-004',
 '2025-06-15 00:00:00+00', null,
 1300, 1700, 'EUR',
 'full_time',
 ARRAY['remote','paid','entry-level','student-friendly']),

('job',
 'UX/UI Designer',
 'Design intuitive interfaces for our SaaS platform used by 200+ property managers across Europe. You will run user research, create wireframes in Figma, and collaborate with engineering to ship features.',
 'Buildium Europe (Cyprus Office)',
 'Nicosia',
 'hybrid',
 'https://example.com/jobs/buildium-ux',
 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
 'manual', 'seed-job-005',
 '2025-06-20 00:00:00+00', null,
 1500, 2100, 'EUR',
 'full_time',
 ARRAY['design','tech','paid','entry-level']),

('job',
 'Healthcare Administrator – Part Time',
 'Support patient coordination, scheduling, and medical records management at a busy private clinic. Ideal for health sciences students seeking practical experience alongside studies.',
 'American Medical Center Nicosia',
 'Nicosia',
 'in_person',
 'https://example.com/jobs/amc-admin',
 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800',
 'manual', 'seed-job-006',
 '2025-06-01 00:00:00+00', null,
 700, 950, 'EUR',
 'part_time',
 ARRAY['healthcare','student-friendly','paid','entry-level']),

('job',
 'Content Writer – Fintech & Crypto',
 'Produce high-quality long-form articles, guides, and social media content about cryptocurrency, DeFi, and digital payments. Fully remote. Must have a strong English writing portfolio.',
 'eToro Cyprus',
 'Remote',
 'remote',
 'https://example.com/jobs/etoro-writer',
 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800',
 'manual', 'seed-job-007',
 '2025-07-01 00:00:00+00', null,
 1100, 1500, 'EUR',
 'full_time',
 ARRAY['marketing','finance','remote','paid']),

('job',
 'Junior Backend Engineer (Node.js)',
 'Work on the API layer powering a fast-growing legal-tech platform serving law firms across the EU. Stack: Node.js, PostgreSQL, Docker, and AWS. Mentorship from senior engineers guaranteed.',
 'Legaltech Ventures CY',
 'Limassol',
 'hybrid',
 'https://example.com/jobs/legaltech-backend',
 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800',
 'manual', 'seed-job-008',
 '2025-08-01 00:00:00+00', null,
 1500, 2000, 'EUR',
 'full_time',
 ARRAY['tech','paid','entry-level']),

('job',
 'Social Media Manager',
 'Own the social presence of a leading Cyprus hospitality brand across Instagram, TikTok, and LinkedIn. Strategy, scheduling, community management, and monthly performance reporting included.',
 'Atlantica Hotels & Resorts',
 'Limassol',
 'in_person',
 'https://example.com/jobs/atlantica-social',
 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800',
 'manual', 'seed-job-009',
 '2025-06-15 00:00:00+00', null,
 1100, 1450, 'EUR',
 'full_time',
 ARRAY['marketing','student-friendly','paid']),

('job',
 'Junior Accountant (Audit Track)',
 'Gain hands-on experience across audit engagements, financial statement reviews, and tax advisory work at one of Cyprus''s Big Four affiliated offices. ACA/ACCA study support provided.',
 'Deloitte Cyprus',
 'Nicosia',
 'in_person',
 'https://example.com/jobs/deloitte-junior-accountant',
 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800',
 'manual', 'seed-job-010',
 '2025-09-01 00:00:00+00', null,
 1300, 1800, 'EUR',
 'full_time',
 ARRAY['finance','entry-level','paid']),

-- ─────────────────────────────────────────────────────────────────────────────
-- 10 INTERNSHIPS
-- ─────────────────────────────────────────────────────────────────────────────

('internship',
 'Software Engineering Internship – Summer 2025',
 'Join our engineering team for a 10-week paid summer internship. Work on real features for our trading platform used by thousands of EU traders. Mentoring, weekly 1-on-1s, and a final project presentation.',
 'Exness Group',
 'Nicosia',
 'hybrid',
 'https://example.com/intern/exness-swe',
 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800',
 'manual', 'seed-intern-001',
 '2025-06-16 00:00:00+00', '2025-08-22 00:00:00+00',
 900, 1100, 'EUR',
 'internship',
 ARRAY['tech','paid','student-friendly','entry-level']),

('internship',
 'Marketing & Communications Intern',
 'Support the marketing department of a Limassol-based luxury yacht charter company. Tasks include content creation, influencer outreach, and campaign analytics. Must be comfortable on social media.',
 'Sea Breeze Yacht Charters',
 'Limassol',
 'in_person',
 'https://example.com/intern/seabreeze-marketing',
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 'manual', 'seed-intern-002',
 '2025-07-01 00:00:00+00', '2025-09-30 00:00:00+00',
 600, 800, 'EUR',
 'internship',
 ARRAY['marketing','paid','student-friendly']),

('internship',
 'Data Science Intern – Healthcare Analytics',
 'Work alongside our medical informatics team to build predictive models for patient outcomes using anonymised hospital datasets. Python, pandas, and Jupyter experience preferred.',
 'Ygia Polyclinic Limassol',
 'Limassol',
 'hybrid',
 'https://example.com/intern/ygia-ds',
 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
 'manual', 'seed-intern-003',
 '2025-06-02 00:00:00+00', '2025-08-29 00:00:00+00',
 750, 950, 'EUR',
 'internship',
 ARRAY['healthcare','tech','paid','entry-level','student-friendly']),

('internship',
 'Finance & Investment Intern',
 'Rotating internship across portfolio analysis, client reporting, and ESG research desks. Ideal for finance, economics, or accounting students. CFA Institute curriculum exposure.',
 'Julius Baer Cyprus',
 'Nicosia',
 'in_person',
 'https://example.com/intern/julius-baer-finance',
 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800',
 'manual', 'seed-intern-004',
 '2025-06-09 00:00:00+00', '2025-08-15 00:00:00+00',
 850, 1050, 'EUR',
 'internship',
 ARRAY['finance','paid','entry-level','student-friendly']),

('internship',
 'UX Research Internship – Remote',
 'Conduct usability testing, user interviews, and survey analysis for a Cyprus-based edtech startup. Deliver actionable insights to the product team. Fully remote with weekly video standups.',
 'EduPath Technologies',
 'Remote',
 'remote',
 'https://example.com/intern/edupath-ux',
 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800',
 'manual', 'seed-intern-005',
 '2025-07-14 00:00:00+00', '2025-09-19 00:00:00+00',
 600, 800, 'EUR',
 'internship',
 ARRAY['design','tech','remote','paid','student-friendly']),

('internship',
 'Legal Internship – EU Regulatory Affairs',
 'Assist the legal team with EU GDPR compliance, contract drafting, and regulatory research for a fintech company with pan-European operations. Law students in their 3rd year and above preferred.',
 'Ancoria Insurance Asset Management',
 'Nicosia',
 'in_person',
 'https://example.com/intern/ancoria-legal',
 'https://images.unsplash.com/photo-1589391886645-d51941baf7fb?w=800',
 'manual', 'seed-intern-006',
 '2025-06-23 00:00:00+00', '2025-09-12 00:00:00+00',
 700, 900, 'EUR',
 'internship',
 ARRAY['finance','entry-level','paid','student-friendly']),

('internship',
 'Graphic Design Intern',
 'Create visual assets for print and digital campaigns including brochures, social media graphics, and exhibition materials. Proficiency in Adobe Creative Suite required. Portfolio submission mandatory.',
 'Hellenic Bank',
 'Nicosia',
 'hybrid',
 'https://example.com/intern/hellenic-design',
 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800',
 'manual', 'seed-intern-007',
 '2025-06-30 00:00:00+00', '2025-09-26 00:00:00+00',
 650, 850, 'EUR',
 'internship',
 ARRAY['design','paid','entry-level','student-friendly']),

('internship',
 'Environmental Sustainability Intern',
 'Support the ESG and sustainability team with carbon footprint reporting, supplier audits, and green initiative coordination. Ideal for environmental science or business sustainability students.',
 'Cyprus Electricity Authority',
 'Nicosia',
 'in_person',
 'https://example.com/intern/eac-sustainability',
 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800',
 'manual', 'seed-intern-008',
 '2025-07-07 00:00:00+00', '2025-09-05 00:00:00+00',
 700, 900, 'EUR',
 'internship',
 ARRAY['sustainability','entry-level','paid','student-friendly']),

('internship',
 'Journalism & Media Internship',
 'Work with the editorial team at Cyprus''s leading English-language news outlet. Responsibilities include researching stories, writing articles, and producing short video content. Published work guaranteed.',
 'Cyprus Mail',
 'Nicosia',
 'in_person',
 'https://example.com/intern/cyprus-mail',
 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800',
 'manual', 'seed-intern-009',
 '2025-06-16 00:00:00+00', '2025-08-08 00:00:00+00',
 500, 700, 'EUR',
 'internship',
 ARRAY['marketing','entry-level','paid','student-friendly']),

('internship',
 'Cloud Infrastructure Intern (AWS)',
 'Help our DevOps team migrate workloads to AWS, write Terraform modules, and set up CI/CD pipelines. Hands-on with real production infrastructure from day one. AWS certification study support provided.',
 'KPMG Cyprus Technology',
 'Limassol',
 'hybrid',
 'https://example.com/intern/kpmg-cloud',
 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
 'manual', 'seed-intern-010',
 '2025-07-01 00:00:00+00', '2025-09-30 00:00:00+00',
 800, 1000, 'EUR',
 'internship',
 ARRAY['tech','paid','entry-level','student-friendly']),

-- ─────────────────────────────────────────────────────────────────────────────
-- 10 VOLUNTEERING
-- ─────────────────────────────────────────────────────────────────────────────

('volunteering',
 'Beach Clean-Up Volunteer – Protaras',
 'Join the monthly coastal clean-up organised by the Cyprus Marine & Maritime Institute. Collect marine litter, record data for the EU Marine Strategy Framework, and help protect the Mediterranean ecosystem.',
 'Cyprus Marine & Maritime Institute',
 'Protaras',
 'in_person',
 'https://example.com/volunteer/cmmi-beach',
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
 'manual', 'seed-vol-001',
 '2025-06-07 08:00:00+00', '2025-06-07 13:00:00+00',
 null, null, 'EUR',
 'volunteer',
 ARRAY['sustainability','student-friendly']),

('volunteering',
 'Refugee Integration Tutoring Program',
 'Provide weekly English and maths tutoring to newly arrived refugee families in Nicosia. Training and materials provided. Minimum 3-hour weekly commitment for at least 2 months.',
 'UNHCR Cyprus & Caritas Cyprus',
 'Nicosia',
 'in_person',
 'https://example.com/volunteer/unhcr-tutoring',
 'https://images.unsplash.com/photo-1529390079861-591de354faf5?w=800',
 'manual', 'seed-vol-002',
 '2025-06-01 00:00:00+00', '2025-08-31 00:00:00+00',
 null, null, 'EUR',
 'volunteer',
 ARRAY['student-friendly','entry-level']),

('volunteering',
 'Food Bank Sorting & Distribution',
 'Help sort donated food items, pack weekly parcels, and assist with distribution events at a Limassol food bank supporting over 300 vulnerable families every month.',
 'Limassol Food Bank Foundation',
 'Limassol',
 'in_person',
 'https://example.com/volunteer/limassol-foodbank',
 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800',
 'manual', 'seed-vol-003',
 '2025-05-31 00:00:00+00', null,
 null, null, 'EUR',
 'volunteer',
 ARRAY['student-friendly']),

('volunteering',
 'Digital Skills Coach for Seniors',
 'Teach basic smartphone and internet skills to elderly residents at a Nicosia community centre. Sessions run every Tuesday and Thursday morning. Patience and good communication skills are essential.',
 'Age Concern Cyprus',
 'Nicosia',
 'in_person',
 'https://example.com/volunteer/age-concern-digital',
 'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=800',
 'manual', 'seed-vol-004',
 '2025-06-03 00:00:00+00', null,
 null, null, 'EUR',
 'volunteer',
 ARRAY['tech','student-friendly','entry-level']),

('volunteering',
 'Animal Shelter Care Assistant',
 'Support the team at Nicosia''s municipal animal shelter with feeding, socialisation, kennel cleaning, and adoption event coordination. Flexible shifts available every weekend.',
 'Nicosia SPCA',
 'Nicosia',
 'in_person',
 'https://example.com/volunteer/nicosia-spca',
 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800',
 'manual', 'seed-vol-005',
 '2025-06-01 00:00:00+00', null,
 null, null, 'EUR',
 'volunteer',
 ARRAY['healthcare','student-friendly']),

('volunteering',
 'Mental Health Awareness Campaign Volunteer',
 'Help produce social media content, organise campus awareness events, and run peer-support listening booths during World Mental Health Week. Training in mental health first aid provided.',
 'Mental Health Cyprus NGO',
 'Remote',
 'hybrid',
 'https://example.com/volunteer/mhcyprus',
 'https://images.unsplash.com/photo-1527689368864-3a821dbccc34?w=800',
 'manual', 'seed-vol-006',
 '2025-10-01 00:00:00+00', '2025-10-12 00:00:00+00',
 null, null, 'EUR',
 'volunteer',
 ARRAY['healthcare','marketing','student-friendly','remote']),

('volunteering',
 'EU Solidarity Corps – Community Gardening',
 'Six-month EU-funded voluntary placement working with an urban community garden project in Paphos. Participants receive accommodation, a monthly allowance, and a Youthpass certificate.',
 'EU Solidarity Corps / Green Paphos',
 'Paphos',
 'in_person',
 'https://example.com/volunteer/eu-solidarity-garden',
 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
 'manual', 'seed-vol-007',
 '2025-09-01 00:00:00+00', '2026-03-01 00:00:00+00',
 null, null, 'EUR',
 'volunteer',
 ARRAY['sustainability','student-friendly','entry-level']),

('volunteering',
 'Hospital Radio & Media Volunteer',
 'Record and broadcast weekly radio programmes for patients at Nicosia General Hospital. Present music shows, interviews, and wellbeing content. Training provided; no experience necessary.',
 'Nicosia General Hospital Volunteers',
 'Nicosia',
 'in_person',
 'https://example.com/volunteer/ngh-radio',
 'https://images.unsplash.com/photo-1478737270197-f45e38ede7b3?w=800',
 'manual', 'seed-vol-008',
 '2025-06-01 00:00:00+00', null,
 null, null, 'EUR',
 'volunteer',
 ARRAY['healthcare','student-friendly']),

('volunteering',
 'Online Maths Tutoring for Underprivileged Students',
 'Volunteer as an online maths tutor for secondary school students from low-income backgrounds across Cyprus. Sessions are 1 hour per week, fully online, and matched by availability.',
 'Cyprus Tutoring for All Initiative',
 'Remote',
 'remote',
 'https://example.com/volunteer/cy-tutoring',
 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=800',
 'manual', 'seed-vol-009',
 '2025-06-01 00:00:00+00', null,
 null, null, 'EUR',
 'volunteer',
 ARRAY['remote','student-friendly','entry-level']),

('volunteering',
 'Graphic Design Volunteer – NGO Communications',
 'Create flyers, social media visuals, and annual report layouts for a Cyprus refugee support charity. Fully remote, flexible hours. Adobe Illustrator or Canva proficiency required.',
 'Refugee Support CY',
 'Remote',
 'remote',
 'https://example.com/volunteer/refugee-support-design',
 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
 'manual', 'seed-vol-010',
 '2025-06-01 00:00:00+00', null,
 null, null, 'EUR',
 'volunteer',
 ARRAY['design','remote','student-friendly']);
